### ISSUE TITLE
Support for hot-reloading certificates

### ISSUE THREAD

**Issue by weeco** [twmb/tlscfg#3]
Maybe that's beyond the desired scope of this project, but support for hot-reloading updated certificates from the filesystem would be really handy. It's a common use-case when serving a TLS protected endpoint which is provided Let's Encrypt certificates that will rotate every 30days or so.

**Comment by twmb** [comment]
Replied on slack -- this _is_ possible, but you have to orchestrate it. To start, this is primarily a dialer concern. You can provide a custom GetCertificate, or more likely, you can provide a custom Dialer that loads a new certificate as necessary.
